vim.api.nvim_set_hl(0, "VertSplit",                    {fg="black", bg="red"})
vim.api.nvim_set_hl(0, "WinSeparator",                 {fg="black", bg="#005f87"})
vim.api.nvim_set_hl(0, "RdStatusLineModeAccent",       {fg="black", bg="#00acc1"})
vim.api.nvim_set_hl(0, "RdStatusLineInsertModeAccent", {fg="black", bg="#ff6e40"})
vim.api.nvim_set_hl(0, "RdStatusLineAccent",           {fg="black", bg="white"})
vim.api.nvim_set_hl(0, "RdStatusLineNCAccent",         {fg="black", bg="darkgrey"})
